export const articles = [
  {
    id: 1,
    title: "Season 1",
    year: "October 3rd, 1987",
    description: "The series follows Micki and Ryan, cousins who inherit an antiques store; after selling all the antiques, they learn from Jack Marshak that the items are cursed. The trio then work together to recover the objects and return them to the safety of the shop's vault. (26 Episodes)",
    category: "Season 1",
    episode1: "S01E01 - The Inheritance",
    episode1detail: "Two cousins, Ryan Dallion and Micki Foster, inherit an antiques shop from their uncle. Together with his partner, they must track down cursed objects that their devil-worshiping uncle had created. The first object is a demonic killer doll.",
    episode2: "S01E02 - The Poison Pen",
    episode2detail: "Ryan and Micki disguise themselves as monks to retrieve a mysterious pen kept in an ancient monastery.",
    episode3: "S01E03 - Cupid's Quiver",
    episode3detail: "Micki, Ryan and Jack must track down an evil statue that causes men to kill the women they love.",
    episode4: "S01E04 - A Cup of Time",
    episode4detail: "A mysterious teacup gives an elderly woman the power of eternal youth -- at a cost.",
    episode5: "S01E05 - Hellowe'en",
    episode5detail: "On Halloween night, Micki and Ryan are visited by the ghost of their late uncle, who has returned from the underworld.",
    episode6: "S01E06 - The Great Montarro",
    episode6detail: "Micki and Ryan track down a box used to perform a dangerous magic trick.",
    episode7: "S01E07 - Doctor Jack",
    episode7detail: "Micki, Ryan and Jack track down a cursed scalpel that has found its way into the hands of a talented surgeon.",
    episode8: "S01E08 - Shadow Boxer",
    episode8detail: "Micki and Ryan investigate the murder of a gym owner and realize that a mysterious pair of boxing gloves may be to blame.",
    episode9: "S01E09 - Root of All Evil",
    episode9detail: "Ryan and Micki search for a cursed mulcher which is the murder weapon of choice for a gardener's assistant.",
    episode10: "S01E10 - Tales of the Undead",
    episode10detail: "Ryan believes that a half-man, half-monster comic-book hero has come to life and is responsible for the murder of a shopkeeper.",
    episode11: "S01E11 - Scarecrow",
    episode11detail: "Micki and Ryan search for a cursed scarecrow that may be responsible for murder.",
    episode12: "S01E12 - Faith Healer",
    episode12detail: "An unscrupulous faith healer discovers a powerful glove that turns him into a killer.",
    episode13: "S01E13 - The Baron's Bride",
    episode13detail: "Micki and Ryan are transported to 1875 London where, aided by an adventurous young writer, they set out to reclaim a cursed object from a bloodthirsty killer.",
    episode14: "S01E14 - Bedazzled",
    episode14detail: "Micki is terrorized by two men looking for a cursed lantern taken from them that has the power to find buried treasure.",
    episode15: "S01E15 - Vanity's Mirror",
    episode15detail: "A girl finds a compact mirror that has the power to make others adore her and uses the cursed object to seek revenge against her sister.",
    episode16: "S01E16 - Tattoo",
    episode16detail: "A compulsive gambler discovers a way to increase his winnings, but the method proves to be deadly.",
    episode17: "S01E17 - The Electrocutioner",
    episode17detail: "A dentist uses a cursed electric chair to seek revenge against those who wronged him.",
    episode18: "S01E18 - Brain Drain",
    episode18detail: "A man seeks to increase his intelligence and become a world-renowned scientist, but his quest results in the deaths of other researchers.",
    episode19: "S01E19 - The Quilt of Hathor",
    episode19detail: "Micki and Ryan pose as members of a religious sect to track down a patchwork quilt that is thought to have deadly powers.",
    episode20: "S01E20 - The Quilt of Hathor : The Awakening",
    episode20detail: "Ryan learns that a woman is using a deadly quilt to murder members of a religious sect, but the tightly-knit group blames him for the killings.",
    episode21: "S01E21 - Double Exposure",
    episode21detail: "Ryan suspects a news anchor of murder, but the man has a solid alibi that makes it nearly impossible to prove he is the culprit.",
    episode22: "S01E22 - The Pirate's Promise",
    episode22detail: "Micki and Ryan travel to a seaside village to retrieve a cursed foghorn that is being used by a town resident to summon the ghost of a vengeful pirate.",
    episode23: "S01E23 - Badge of Honor",
    episode23detail: "A police officer uses a deadly sheriff's badge to seek revenge against a mob boss for the murder of his wife.",
    episode24: "S01E24 - Pipe Dream",
    episode24detail: "A frustrated dreamer turns to the supernatural to achieve success, using an ornate pipe to eliminate anyone who gets in his way.",
    episode25: "S01E25 - What a Mother Wouldn't Do",
    episode25detail: "A woman is driven to murder when her newborn's cursed cradle seeks revenge.",
    episode26: "S01E26 - Bottle of Dreams",
    episode26detail: "Jack tries to rescue Ryan and Micki when they're locked in a vault with a mystic urn that conjures up torturous nightmares.",
    episodes: "The Inheritance - The Poison Pen - Cupid's Quiver - A Cup of Time - Hellowe'en - The Great Montarro - Doctor Jack - Shadow Boxer - Root of All Evil - Tales of the Undead - Scarecrow - Faith Healer - The Baron's Bride - Bedazzled - Vanity's Mirror - Tattoo - The Electrocutioner - Brain Drain - The Quilt of Hathor - The Quilt of Hathor: The Awakening - Double Exposure - The Pirate's Promise - Badge of Honor - Pipe Dream - What a Mother Wouldn't Do - Bottle of Dreams",
    image: "/articles/fridaytvs1.jpg",
  },
  {
    id: 2,
    title: "Season 2",
    year: "September 26th, 1988",
    description: "The series follows Micki and Ryan, cousins who inherit an antiques store; after selling all the antiques, they learn from Jack Marshak that the items are cursed. The trio then work together to recover the objects and return them to the safety of the shop's vault. (26 Episodes)",
    category: "Season 2",
    episode1: "S02E01 - Doorway to Hell",
    episode1detail: "A cracked mirror threatens to suck Micki and Ryan into the underworld.",
    episode2: "S02E02 - The Voodoo Mambo",
    episode2detail: "The spirit of a dead voodoo priestess strikes out at three voodoo Legbas to get their power and resurrect herself, and take revenge on the fourth Legba, who killed her.",
    episode3: "S02E03 - And Now The News",
    episode3detail: "A psychiatrist secretly accounts her miraculous success rate to a unique antique radio that delivers cures and advice during the nightly news.",
    episode4: "S02E04 - Tails I Live, Heads You Die",
    episode4detail: "A reporter trails a violent cult of devil worshipers calling people back from the dead.",
    episode5: "S02E05 - Symphony in B-Sharp",
    episode5detail: "Micki and Ryan investigate a series of murders at a concert hall, only to discover that a violinist who was presumed dead may in fact be alive.",
    episode6: "S02E06 - Master of Disguise",
    episode6detail: "Micki learns beauty is only skin deep after she falls for a mysterious movie star who relies on an antique makeup case.",
    episode7: "S02E07 - Wax Magic",
    episode7detail: "Ryan and Jack are intrigued by a traveling wax museum that boasts an exhibit of axe murderess Lizzie Andrew Borden.",
    episode8: "S02E08 - Read My Lips",
    episode8detail: "A ventriloquist's dummy becomes a vessel for evil when it comes to life and demands that its master commit murder.",
    episode9: "S02E09 - 13 O'Clock",
    episode9detail: "Ryan, Micki and Jack track down an antique pocket watch that allows its owner to freeze time.",
    episode10: "S02E10 - Night Hunger",
    episode10detail: "A hot-rod racer uses a cursed necklace to win events by killing his competition and dipping the chain in his victims' blood.",
    episode11: "S02E11 - The Sweetest Sting",
    episode11detail: "Micki, Ryan and Jack pursue an antique beehive containing vampire bees that suck the life out of their victims.",
    episode12: "S02E12 - The Playhouse",
    episode12detail: "Micki, Ryan and Jack travel to a small town where the disappearance of several children is linked to a mysterious toy playhouse.",
    episode13: "S02E13 - Eye of Death",
    episode13detail: "A devious antiques dealer uses a magic lantern to travel back to the Civil War so he can steal artifacts from dead soldiers.",
    episode14: "S02E14 - Face of Evil",
    episode14detail: "A model uses a cursed compact to dispose of anyone who stands in the way of her success, including her doctor and her lover.",
    episode15: "S02E15 - Better Off Dead",
    episode15detail: "Micki is captured by a deranged scientist who uses an antique silver syringe to extract brain fluids from prostitutes.",
    episode16: "S02E16 - Scarlet Cinema",
    episode16detail: "A college student dreams of becoming a werewolf and discovers an antique camera that will turn him into his favorite movie monster.",
    episode17: "S02E17 - The Mephisto Ring",
    episode17detail: "Micki and Ryan race to find an old World Series ring that enables its owner to see gambling results before they happen.",
    episode18: "S02E18 - A Friend to the End",
    episode18detail: "Micki's young nephew befriends the reanimated corpse of a boy residing in the local haunted house.",
    episode19: "S02E19 - The Butcher",
    episode19detail: "A Nazi scientist uses a cursed amulet to bring a Nazi colonel back to life in order to kill Jack and his old army buddies.",
    episode20: "S02E20 - The Secret Agenda of Mesmer's Bauble",
    episode20detail: "A record store clerk with psychotic tendencies is granted unspeakable powers by a magical pendant, which he abuses to fulfill his dream of meeting a beautiful rock star.",
    episode21: "S02E21 - Wedding in Black",
    episode21detail: "Micki, Jack and Ryan become suspicious when they each receive mysterious visits from three friends from their past.",
    episode22: "S02E22 - Wedding Bell Blues",
    episode22detail: "Micki waits tables in a seedy bar in an attempt to retrieve a cursed pool cue that enables the owner to win every game.",
    episode23: "S02E23 - The Maestro",
    episode23detail: "Ryan and Micki investigate the apparent suicides of a handful of ballet dancers and soon learn that they may be linked to a rare music box.",
    episode24: "S02E24 - The Shaman's Apprentice",
    episode24detail: "A native American doctor discovers a unique way to cure terminally ill patients, but the price of the treatment is murder.",
    episode25: "S02E25 - The Prisoner",
    episode25detail: "A prisoner acquires a jacket that renders him invisible, allowing him to walk out of jail and get revenge on those who betrayed him.",
    episode26: "S02E26 - Coven of Darkness",
    episode26detail: "A witch fights to gain a powerful occult symbol, using a helpless Ryan in the process.",
    episodes: "Doorway to Hell - The Voodoo Mambo - And Now The News - Tails I Live, Heads You Die - Symphony in B-Sharp - Master of Disguise - Wax Magic - Read My Lips - 13 O'Clock - Night Hunger - The Sweetest Sting - The Playhouse - Eye of Death - Face of Evil - Better Off Dead - Scarlet Cinema - The Mephisto Ring - A Friend to the End - The Butcher - The Secret Agenda of Mesmer's Bauble - Wedding in Black - Wedding Bell Blues - The Maestro - The Shaman's Apprentice - The Prisoner - Coven of Darkness",
    image: "/articles/fridaytvs2.jpg",
  },
  {
    id: 3,
    title: "Season 3",
    year: "October 7th, 1989",
    description: "The series follows Micki and Ryan, cousins who inherit an antiques store; after selling all the antiques, they learn from Jack Marshak that the items are cursed. The trio then work together to recover the objects and return them to the safety of the shop's vault. (20 Episodes)",
    category: "Season 3",
    episode1: "S03E01 - The Prophecies: Part 1",
    episode1detail: "Micki and Ryan travel to a French village to help Jack stop a fallen angel from fulfilling six evil prophecies.",
    episode2: "S03E02 - The Prophecies: Part 2",
    episode2detail: "Ryan is turned into a servant of the devil and the only hope he has is a young girl who believes in God's love.",
    episode3: "S03E03 - Demon Hunter",
    episode3detail: "A family of militia types is being hunted by a demon.",
    episode4: "S03E04 - Crippled Inside",
    episode4detail: "A vengeful quadriplegic discovers that she can regain control of her body with the help of a magic wheelchair.",
    episode5: "S03E05 - Stick It in Your Ear",
    episode5detail: "A commercial psychic uses a mystic hearing aid to read the thoughts of his audience.",
    episode6: "S03E06 - Bad Penny",
    episode6detail: "Micki discovers that a deadly item from her past has resurfaced, a satanic coin that can bring the dead back to life.",
    episode7: "S03E07 - Hate on Your Dial",
    episode7detail: "A racist uses a cursed antique car radio to travel back to 1954 and tries to prevent the arrest and death of his father, a member of the KKK.",
    episode8: "S03E08 - Night Prey",
    episode8detail: "A cursed crucifix helps a husband exact revenge on the vampire who stole his bride during their honeymoon in 1969.",
    episode9: "S03E09 - Femme Fatale",
    episode9detail: "A director lures women into his home where they become unwilling players in his movies thanks to a cursed film reel.",
    episode10: "S03E10 - Mightier Than the Sword",
    episode10detail: "Using a cursed pen, a pulp writer transforms himself into an acclaimed novelist who is known for getting inside the minds of serial killers.",
    episode11: "S03E11 - Year of the Monkey",
    episode11detail: "A father uses a potentially fatal test to challenge the loyalty of his children using three magical monkey statues.",
    episode12: "S03E12 - Epitaph for a Lonely Soul",
    episode12detail: "A mortician uses a cursed embalming tool to re-animate the corpse of a woman with whom he becomes obsessed after she dies.",
    episode13: "S03E13 - Midnight Riders",
    episode13detail: "History repeats itself when a gang of bikers return from the dead to wreak small-town terror.",
    episode14: "S03E14 - Repetition",
    episode14detail: "A well-known columnist is transformed into a desperate killer after finding a cursed locket in his possession.",
    episode15: "S03E15 - The Long Road Home",
    episode15detail: "Micki and Johnny must use a charm that transfers one person's mind into another's body.",
    episode16: "S03E16 - My Wife as a Dog",
    episode16detail: "A neurotic man uses a cursed dog leash to transform his wife into an obedient and faithful canine.",
    episode17: "S03E17 - Jack-in-the-Box",
    episode17detail: "An angry child avenges her father's senseless death using a cursed toy.",
    episode18: "S03E18 - Spirit of Television",
    episode18detail: "A dying woman uses the powers of a cursed TV set to convince people that she's a medium - and push back the hour of her own death.",
    episode19: "S03E19 - The Tree of Life",
    episode19detail: "An obstetrician practicing Druidism utilizes a cursed statue to breed Druid priestesses at her fertility clinic.",
    episode20: "S03E20 - The Charnel Pit",
    episode20detail: "A two-sided painting acts as a portal back to the time of the Marquis de Sade.",
    episodes: "The Prophecies: Part 1 - The Prophecies: Part 2 - Demon Hunter - Crippled Inside - Stick It in Your Ear - Bad Penny - Hate on Your Dial - Night Prey - Femme Fatale - Mightier Than The Sword - Year of the Monkey - Epitaph for a Lonely Soul - Midnight Riders - Repetition - The Long Road Home - My Wife as a Dog - Jack-in-the-Box - Spirit of Television - The Tree of Life - The Charnel Pit",
    image: "/articles/fridaytvs3.jpg",
  },
  {
    id: 4,
    title: "Crystal Lake",
    year: "Expected release in 2023",
    description: "A new series based on the Friday the 13th franchise. Prequel series to Friday the 13th, follows a doomed small town where camp counselors come to die.",
    episode1: "To Be Determined",
    category: "Crystal Lake",
    image: "/articles/fridaytvs4.jpg",
  }
]